---
title: "AE 07: Price of Textbooks cont'd"
subtitle: "SLR: Partitioning variability"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_height: 3
    fig_width: 6
    theme: readable
    code_folding: hide
---

```{r include = F}
knitr::opts_chunk$set(warning = F, 
                      message = F)
```


## Class announcements

- See this week's schedule: [Week 04](https://sta210-sp21.netlify.app/schedule/week-04/)
  - [Lab 03](https://sta210-sp21.netlify.app/labs/lab-02-durham-trails.html) due Sun, Feb 14 at 11:59p
  - [HW 02](https://sta210-sp21.netlify.app/hw/hw-01.html) due Wed Feb 17 at 11:5p EST. Repos available after class

## Normal QQ plots

```{r fig.height = 6}

library(tidyverse)
library(patchwork)

set.seed(1234)
norm_data <- tibble(x = rnorm(1000,0,1))
norm_hist <- ggplot(data = norm_data, aes(x = x)) + 
  geom_histogram()

norm_qq <- ggplot(data = norm_data, aes(sample = x)) + 
  stat_qq() + stat_qq_line()

right_data <- tibble(x = rbeta(1000, 2, 8))
right_hist <- ggplot(data = right_data, aes(x = x)) + 
  geom_histogram()
right_qq <- ggplot(data = right_data, aes(sample = x)) + 
  stat_qq() + stat_qq_line()

left_data <- tibble(x = rbeta(1000,8,2))
left_hist <- ggplot(data = left_data, aes(x = x)) + 
  geom_histogram()
left_qq <- ggplot(data = left_data, aes(sample = x)) + 
  stat_qq() + stat_qq_line()

(norm_hist + norm_qq) / (right_hist + right_qq) / (left_hist + left_qq)
```


    
## Questions from video

##  AE 07: Price of textbooks

Clone the **ae-07** repo and open a new project in RStudio. Be sure to push your work periodically as you complete the AE.

Go the breakout room for your lab group.

