---
title: "Project Peer Review"
subtitle: "due Mon, Apr 19 at 11:59p EDT"
output: 
  tufte::tufte_html:
    highlight: pygments
    css: "sta210-labs.css"
link-citations: yes
---

```{r include=FALSE}
library(tidyverse)
library(tufte)
library(knitr)
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  digits = 2
  )
knitr::opts_chunk$set(eval = FALSE)
```

Critically reviewing others' work is a crucial part of the scientific process, and STA 210 is no exception. Each group has been given read access to another group's repo to review and provide feedback on their project draft. This review is intended to help you create a high quality final project, as well as give you experience  reading and constructively critiquing the work of others. 

To ensure the group has enough time to start incorporating feedback ,you should work on the peer review during lab and submit comments by **Mon, Apr 19 at 11:59p EDT**. 

# Getting started 

[Click here](https://prodduke-my.sharepoint.com/:x:/g/personal/mt324_duke_edu/EU-dNt2OTKJNsaQTINWQnFABQSp7ihfGdPZJo22FL3aKog?e=huCxFf) to see which project you're reviewing. 

Then, search your GitHub repositories for `project` and you should see the repo for the project you're reviewing. 

# Reviewing the draft

Carefully read the project draft, considering the questions below as you read it. 

You will submit your review by creating new **Issues** in the team's GitHub repo. To do so, 

- Go to the team's repo and click **Issues**. 
- Click **New issue**. 
- You will see several options that begin with "Peer review". Click **Get started** and it will open a new issue. 
- Type your response under each question header. 

# Peer review questions

Your response to each question will have two parts: 

- Selection of one of the following: 
  
  - **Yes**: The item is clearly and accurately completed in the draft. 
  - **Somewhat**: There is an attempt to complete the item in the draft; however, it is incomplete or there are some inaccuracies. 
  - **No**: There is no attempt to complete the item in the draft, or there are major inaccuracies. 

- Brief comment about your selection.
  
  - If you responded **Yes**, briefly summarize the answer from the draft. For example, if you answer **yes** that the draft includes citations for outside research, briefly summarize what that outside research is.
  - If you responded **Somewhat** or **No**, briefly summarize what is incomplete or inaccurate. In other words, briefly summarize why you did not respond Yes to that item.

## Issue 1: Introduction + Data

- Is the research question and goal of the report clearly stated? 
- Does the introduction provide appropriate background context and motivation for a general reader? This includes citations for any claims or previous research mentioned.
- Is the original source of the data stated and cited?
- Is it clear when and how the data was originally collected?
- Are the observations and variables that are relevant to the analysis clearly described? At a minimum, the observations, response variable, and predictor variables in the final model should be clearly described.
- Include any additional comments or suggestions on the introduction and data description. 

## Issue 2: Exploratory data analysis 

- Is the data cleaning and data wrangling process clearly described? This includes how the group handled missing data, created new variables, reduced the number of levels for categorical variables, etc.
- Do the visualizations follow the guidelines we've discussed in STA 210? This includes using plots that are appropriate for the data, having proper axis labels, titles, etc. 
- Are any tables and figures clear, effective, and informative? Are they neatly printed with a reasonable number of digits displayed? 
- Should any visualizations, figures, or tables be eliminated, or are there any new visualizations, tables, or figures that should be added?
- Include any additional comments or suggestions for the exploratory data analysis. 

## Issue 3: Methodology + Results

- Do the regression methods (linear or logistic regression) match the research question(s) and available data? If not, point out areas for further work. 
- Are the methods described in enough detail that the work could be replicated by someone else? Is it clear what approach and model were used to evaluate hypotheses of interest?  If not, point out areas for further work.
- Is the model selection accurately performed, if at all?  
- What type of diagnostic methods were used to check any modeling conditions, and are you satisfied the conditions of the model are valid? Should any additional analyses be performed?
- Did the group consider any interaction terms?
- Does the report contain a correct and effective interpretation of the results provided? Is all information needed to substantiate the results and conclusions included?  If not, point out areas for further work.

## Issue 4: Presentation + general comments

- Is the paper professionally presented and generally free of distracting errors or other issues, including (but not limited to) insufficient organization or formatting; poor grammar, spelling, or punctuation? Is the overall paper easily readable for someone with your expert level of knowledge? Note any concerns here.
- What is one question you have about the data and/or analysis that isn't yet addressed in the report?


### Applying to your project 

**Discuss the following as a group. You do <u>not</u> need to submit a response to this question.**

After giving feedback to this group, what is one thing you want to change or continue working on for your report? 

# Submission

The peer review will be graded on the extent to which it comprehensively and
constructively addresses the components of the partner team's report: the 
research context and motivation, exploratory data analysis, reproducibility,
and any inference, modeling, or conclusions. 

You will be graded based on the submitted issues on GitHub.

